### PR TITLE
feat: Implement export all student customers

### LINKED ISSUE #502: Implement export all student customer
### Feature Description

A CSV download should trigger when a user clicks export button
image

### Use Case

_No response_

### Proposed Solution

1. Write a supabase edge function
2. Use this query to fetch the data
```
select distinct "profile"."id", "profile"."email", "profile"."fullname"
from
  "public"."organization" as "org"
join "public"."group" as "group" on "org"."id" = "group"."organization_id"
join "public"."groupmember" as "groupmember" on "groupmember"."group_id" = "group"."id"
join "public"."profile" as "profile" on "profile"."id" = "groupmember"."profile_id"
where "groupmember"."role_id" = 3 and "org"."id" = 'SOME_ORG_ID_HERE'
limit
  1000;
```

### Alternatives (optional)

_No response_

### Additional Context

_No response_

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

### PR DESCRIPTION
**Pull request by Tamunokorite**
## What does this PR do?

Implemented the requested feature to export all student customers as a CSV file, with the specified SQL query.

Fixes #502

Screenshot 2024-11-16 at 03 32 06

https://github.com/user-attachments/assets/84c2e581-ff71-4d17-96d2-bee85b3cc211

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Follow the [docs](https://github.com/classroomio/classroomio/blob/main/README.md) to setup the project locally
- Login to the dashboard with the test admin credentials
- Navigate to audience page
- Click export

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

### CODE REVIEW

**Review by rotimi-best — CHANGES_REQUESTED** [review]
Hi @Tamunokorite, thank you so much for this PR.

I see you are using a db function + an edge function to implement this functionality.

I will recommend a simpler approach. We already have a js function called `getOrgAudience` (please check it out). That function makes the query already to get the audience of an organisation.

I will recommend you abstract only the query part into a function, then create a seperate function called `getOrgAudienceCSV`
image


With this function `getOrgAudienceCSV` you can ask supabase to give you the output data as csv https://supabase.com/docs/reference/javascript/db-csv.

That way you don't need
- csv parsing whatsoever
- a new db function
- any edge function.

Please let me know if this makes sense.

**Comment by Tamunokorite** [comment]
> Hi @Tamunokorite, thank you so much for this PR.
> 
> I see you are using a db function + an edge function to implement this functionality.
> 
> I will recommend a simpler approach. We already have a js function called `getOrgAudience` (please check it out). That function makes the query already to get the audience of an organisation.
> 
> I will recommend you abstract only the query part into a function, then create a seperate function called `getOrgAudienceCSV` image
> 
> With this function `getOrgAudienceCSV` you can ask supabase to give you the output data as csv https://supabase.com/docs/reference/javascript/db-csv.
> 
> That way you don't need
> 
> * csv parsing whatsoever
> * a new db function
> * any edge function.
> 
> Please let me know if this makes sense.

@rotimi-best Got it. It does make sense. Working on the changes now.

**Comment by rotimi-best** [comment]
@Tamunokorite Any updates on this?

**Comment by rotimi-best** [comment]
Closing PR for inactivity

**Pull request closed without merging**
