### PR TITLE
feat: add recommended blog post depending on current post tags

### LINKED ISSUE #495: Add 2 recommended blog post depending on current post tags
### Feature Description

In every blog post there are tags, when we open a blog post at the bottom, let's add 2 recommended blog posts with similar tags

image

### Use Case

_No response_

### Proposed Solution

_No response_

### Alternatives (optional)

_No response_

### Additional Context

_No response_

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

### PR DESCRIPTION
**Pull request by Dun-sin**
## What does this PR do?
- created a component for blog listing called BlogListItem.svelte so, it can be reused for showing other blogs in the current blog
- fetched the blogs available
- filtered the blogs using the tags 
- check how many tags are similar with the current blog tags, based on how many tags are related we then shuffle and suggest 2 blogs excluding the current blog

Fixes #495

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- go to the blogs section
- click on any random blog
- scroll to the end and find the suggested blogs section

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

https://github.com/user-attachments/assets/6e7caf50-ae62-47b8-a5e3-0ab07d4b4286

### CODE REVIEW

**Comment by rotimi-best** [comment]
This is amazing @Dun-sin, thank you.
I will take a look ASAP

**Comment by rotimi-best** [comment]
@Dun-sin i just watched the video, can we make the recommended posts in a horizontal scroll?

Something like this

https://blog.google/outreach-initiatives/diversity/google-veterans-day-2024/

https://github.com/user-attachments/assets/fec02d94-bc84-439f-bb4d-9e27951368ba

**Comment by Dun-sin** [comment]
@rotimi-best done

**Review by rotimi-best — APPROVED** [review]
Thank you so much @Dun-sin.

You rock 🤘 🎸

**Pull request merged**
